pcplus_download_url: "https://download.afd.co.uk/Support/COMPA14.zip"
pcplus_local_zip_path: "/tmp/COMPA14.zip"
pcplus_extract_path: "/tmp/COMPA14"
pcplus_s3_bucket: "shared-services.eu-west-2.resources.ch.gov.uk"
pcplus_s3_prefix: "pcplus"
pcplus_ec2_install_path: "/opt/pcplus"
pcplus_year: "{{ ansible_date_time.year }}"
pcplus_quarter: "Q{{ ((ansible_date_time.month | int - 1) // 3) + 1 }}"
pcplus_new_folder: "{{ pcplus_year }}_{{ pcplus_quarter }}"
pcplus_old_folder: "{{ (pcplus_year | int -1) }}_{{ pcplus_quarter }}"
