---
#- name: Preflight | Validate variables
#  ansible.builtin.assert:
#    that:
#      -pcplus_s3_stage_work_dir | length > 0
#      - pcplus_s3_stage_download_url is match('^https?://')
#      - pcplus_s3_stage_s3_bucket | length > 0
#      - pcplus_s3_stage_aws_region | length > 0
#    fail_msg: "Variable validation failed"
#
- name: Preflight | AWS CLI present
  block:
    - name: Check aws --version
      ansible.builtin.command: aws --version
      register: pcplus_s3_stage__awscli
      changed_when: false
      failed_when: pcplus_s3_stage__awscli.rc != 0
  rescue:
    - name: Fail when aws CLI is missing
      ansible.builtin.fail:
        msg: "AWS CLI missing on localhost"

- name: Preflight | Verify AWS role/session
  block:
    - name: Check aws region
      ansible.builtin.command: >
        aws sts get-caller-identity --region {{ pcplus_s3_stage_aws_region }}
      register: pcplus_s3_stage__stage__sts
      changed_when: false
      failed_when: pcplus_s3_stage__sts.rc != 0
  rescue:
    - name: Check authentication
      ansible.builtin.fail:
        msg: "Unable to authenticate to AWS using Infrastructure role."

- name: Create working directory
  ansible.builtin.file:
    path: "{{ pcplus_s3_stage_work_dir }}"
    state: directory
    mode: "0755"

- name: Download COMPA14.zip
  block:
    - name: Get zip file
      ansible.builtin.get_url:
        url: "{{ pcplus_s3_stage_download_url }}"
        dest: "{{ pcplus_s3_stage_work_dir }}/COMPA14.zip"
        mode: "0644"
      register: pcplus_s3_stage__dl
      retries: 3
      delay: 5
      until: pcplus_s3_stage__dl is succeeded
  rescue:
    - name: Download zip file
      ansible.builtin.fail:
        msg: "Download failed"

- name: Unzip COMPA14.zip
  block:
    - name: Check for zip file
      ansible.builtin.unarchive:
        src: "{{ pcplus_s3_stage_work_dir }}/COMPA14.zip"
        dest: "{{ pcplus_s3_stage_work_dir }}"
        remote_src: true
  rescue:
    - name: Zip file download failed
      ansible.builtin.fail:
        msg: "Failed to unzip COMPA14.zip"

- name: Show types for debugging
  ansible.builtin.debug:
    msg:
      month_type: "{{ pcplus_s3_stage__month | type_debug }}"
      year_type: "{{ pcplus_s3_stage__year | type_debug }}"


- name: Create S3 folder for current quarter
  block:
    - name: Current quater folder
      ansible.builtin.command: >
        aws s3api put-object
        --bucket {{ pcplus_s3_stage_s3_bucket }}
        --key "{{ pcplus_s3_stage_s3_prefix }}/{{ pcplus_s3_stage_current_quarter }}/"
        --region {{ pcplus_s3_stage_aws_region }}
      register: pcplus_s3_stage__mk
      changed_when: pcplus_s3_stage__mk.rc == 0
      failed_when: pcplus_s3_stage__mk.rc != 0
  rescue:
    - name: Quater folder not created
      ansible.builtin.fail:
        msg: "Failed to create S3 prefix."

- name: Check if old quarter exists
  ansible.builtin.command: >
    aws s3 ls s3://{{ pcplus_s3_stage_s3_bucket }}/{{ pcplus_s3_stage_s3_prefix }}/{{ pcplus_s3_stage_old_quarter }}/
  register: pcplus_s3_stage__old
  failed_when: false
  changed_when: false

- name: Delete old quarter folder
  block:
    - name: Remove old quater folder
      ansible.builtin.command: >
        aws s3 rm
        s3://{{ pcplus_s3_stage_s3_bucket }}/{{ pcplus_s3_stage_s3_prefix }}/{{ pcplus_s3_stage_old_quarter }}/
        --recursive
        --region {{ pcplus_s3_stage_aws_region }}

      register: pcplus_s3_stage__rm_old
      changed_when: "'delete:' in pcplus_s3_stage__rm_old.stdout"
      failed_when: pcplus_s3_stage__rm_old.rc != 0

  rescue:
    - name: Old quater folder removed
      ansible.builtin.debug:
        msg: "Old quarter delete failed"

- name: Upload pcplus data
  block:
    - name: Copy pcplus data
      ansible.builtin.command: >
        aws s3 cp --recursive
        "{{ pcplus_s3_stage_work_dir }}/COMPA14/pcplus/data/"
        "s3://{{ pcplus_s3_stage_s3_bucket }}/{{ pcplus_s3_stage_s3_prefix }}/{{ pcplus_s3_stage_current_quarter }}/"
        --region {{ pcplus_s3_stage_aws_region }}
      register: pcplus_s3_stage__up
      retries: 3
      delay: 5
      until: pcplus_s3_stage__up.rc == 0
      changed_when: "'upload:' in _upload.stdout"
      failed_when: _upload.rc != 0

  rescue:
    - name: Fail S3 upload
      ansible.builtin.fail:
        msg: "S3 upload failed"

- name: Copy license if needed
  block:
    - name: Copy licence to current quater
      ansible.builtin.command: >
        aws s3 cp
        "s3://{{ pcplus_s3_stage_s3_bucket }}/{{ pcplus_s3_stage_s3_prefix }}/{{ pcplus_s3_stage_old_quarter }}/pcplus.lic"
        "s3://{{ pcplus_s3_stage_s3_bucket }}/{{ pcplus_s3_stage_s3_prefix }}/{{ pcplus_s3_stage_current_quarter }}/"
        --region {{ pcplus_s3_stage_aws_region }}
      register: pcplus_s3_stage__copy_lic
      changed_when: "'copy:' in _copy_lic.stdout"
      failed_when: _copy_lic.rc != 0
      when: _cur_lic.rc != 0 and _old_lic.rc == 0
  rescue:
    - name: Warn when license copy fails
      ansible.builtin.debug:
