
afd_zip_url: "https://download.afd.co.uk/Support/COMPA14.zip"
download_dir: "/Users/{{ lookup('env','USER') }}/Downloads"
extract_dir: "{{ download_dir }}/COMPA14"
bucket_name: "shared-services.eu-west-2.resources.ch.gov.uk"
s3_pcplus_prefix: "pcplus"
aws_profile_shared: "ch-shared-services"
aws_profile_heritage: "heritage-staging-eu-west-2"
pcplus_dir: "/opt/pcplus"
current_quarter: "{{ '%Y_Q%q' | strftime }}"
