---
- name: Preflight | Ensure pcplus directory exists
  ansible.builtin.file:
    path: "{{ pcplus_run_server_update_pcplus_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Preflight | Check AWS CLI
  block:
    - name: Check for aws CLI
      ansible.builtin.command: aws --version
      register: pcplus_run_server_update__aws
      changed_when: false
      failed_when: pcplus_run_server_update__aws.rc != 0
  rescue:
    - name: Verify aws cli installation
      ansible.builtin.fail:
        msg: "AWS CLI missing on EC2"

- name: Create directory for new quarter
  ansible.builtin.file:
    path: "{{ pcplus_run_server_update_target_dir }}"
    state: directory
    mode: "0755"

- name: Copy data from S3
  block:
    - name: S3 data copy
      ansible.builtin.command: >
        aws s3 cp --recursive
        s3://{{ pcplus_run_server_update_s3_bucket }}/{{ pcplus_run_server_update_s3_prefix }}/{{ pcplus_run_server_update_current_quarter }}/
        "{{ pcplus_run_server_update_target_dir }}/"
        --region {{ pcplus_run_server_update_aws_region }}
      register: pcplus_run_server_update__dl
      retries: 3
      delay: 5
      until: pcplus_run_server_update__dl.rc == 0
      changed_when: "'download:' in pcplus_run_server_update__dl.stdout"
      failed_when: pcplus_run_server_update__dl.rc != 0

  rescue:
    - name: Fail when S3 download to EC2 fails
      ansible.builtin.fail:
        msg: "Failed to fetch S3 data for {{ current_quarter }} into {{ target_dir }}"

- name: Check if pcplus.lic already exists
  ansible.builtin.stat:
    path: "{{ pcplus_run_server_update_target_dir }}/pcplus.lic"
  register: pcplus_lic_stat
  become: true

- name: Copy pcplus.lic from S3 to /opt/pcplus/quater-folder
  ansible.builtin.command: >
    aws s3 cp
    s3://shared-services.eu-west-2.resources.ch.gov.uk/pcplus/pcplus.lic
    {{ pcplus_run_server_update_target_dir }}/pcplus.lic
    --region eu-west-2
  register: pcplus_s3_copy
  retries: 3
  delay: 5
  until: pcplus_s3_copy.rc == 0
  changed_when: "'download:' in pcplus_s3_copy.stdout"
  failed_when: pcplus_s3_copy.rc != 0
  become: true

- name: Ensure correct permissions
  ansible.builtin.file:
    path: "{{ pcplus_run_server_update_target_dir }}"
    owner: root
    group: root
    mode: "0755"
    recurse: true

- name: Backup old data folder
  block:
    - name: Save old data
      ansible.builtin.stat:
        path: "{{ pcplus_run_server_update_pcplus_dir }}/data_{{pcplus_run_server_update_old_quarter}}"
      register: pcplus_run_server_update__old
    - name: Replace old quater with new quater
      ansible.builtin.command:
        cmd: >
          mv "{{ pcplus_run_server_update_pcplus_dir }}/data_{{pcplus_run_server_update_old_quarter}}"
          "{{ pcplus_run_server_update_pcplus_dir }}/backup_{{ ansible_date_time.epoch }}"
      register: pcplus_run_server_update__swap_mv
      when: pcplus_run_server_update__old.stat.exists
      changed_when: pcplus_run_server_update__swap_mv.rc == 0
      failed_when: pcplus_run_server_update__swap_mv.rc != 0

  rescue:
    - name: Check backup status
      ansible.builtin.fail:
        msg: "Failed to backup existing data folder"

- name: Check new quarter directory exists
  ansible.builtin.stat:
    path: "{{ pcplus_run_server_update_pcplus_dir }}/data_{{ pcplus_run_server_update_current_quarter }}"
  register: new_quarter_dir

- name: Check old quarter directory exists
  ansible.builtin.stat:
    path: "{{ pcplus_run_server_update_pcplus_dir }}/data_{{ pcplus_run_server_update_old_quarter }}"
  register: old_quarter_dir

- name: Delete old quarter folder if new quarter exists
  ansible.builtin.file:
    path: "{{ pcplus_run_server_update_pcplus_dir }}/data_{{ pcplus_run_server_update_old_quarter }}"
    state: absent
  when:
    - new_quarter_dir.stat.exists
    - new_quarter_dir.stat.isdir
    - old_quarter_dir.stat.exists
    - old_quarter_dir.stat.isdir

- name: Validate final state
  ansible.builtin.stat:
    path: "{{ pcplus_run_server_update_target_dir }}/data"
  register: pcplus_run_server_update__final

- name: Assert final update completed
  ansible.builtin.assert:
    that:
      - pcplus_run_server_update__final.stat.exists
      - pcplus_run_server_update__final.stat.isdir
    success_msg: "PCPlus server update complete"
    fail_msg: "Data replacement failed"

# - name: Test postcode lookup
#  ansible.builtin.shell: >
#    set -o pipefail
#    /opt/pcplus/bin_linux64/console/addresslookup  postcode="{{pcplus_run_server_update_afd_code}}" | head -10
#  args:
#    executable: /bin/bash
#  register: pcplus_run_server_update_postcode_output
#  changed_when: false
