
---
- block:
    - name: Download COMPA14 ZIP
      get_url:
        url: "{{ afd_zip_url }}"
        dest: "{{ download_dir }}/COMPA14.zip"
#      register: zip_result
#      failed_when: zip_result.status != 200

    - name: Extract ZIP
      unarchive:
        src: "{{ download_dir }}/COMPA14.zip"
        dest: "{{ extract_dir }}"
        remote_src: no
#      register: ex
#      failed_when: ex.failed.status != 100

  rescue:
    - debug:
        msg: "Failed to download or extract COMPA14 files"
    - meta: end_play
