
---
- block:
    - name: List S3 quarterly folders
      command: >
        aws s3 ls s3://{{ bucket_name }}/{{ s3_pcplus_prefix }}/ --profile {{ aws_profile_shared }}
      register: s3_folders
      failed_when: s3_folders.rc != 0

    - name: Parse folder names
      set_fact:
        pcplus_folders: >-
          {{ s3_folders.stdout_lines | map('regex_search', '^(\d{4}_Q\d)', '\1') | select('string') | list }}

    - name: Ensure at least one folder exists
      fail:
        msg: " No quarterly folders found in S3!"
      when: pcplus_folders | length == 0

    - name: Sort quarters
      set_fact:
        sorted_pcplus_folders: "{{ pcplus_folders | sort }}"
        oldest_quarter: "{{ sorted_pcplus_folders[0] }}"
        previous_quarter: "{{ sorted_pcplus_folders[-1] }}"

    - name: Delete oldest quarter
      command: >
        aws s3 rm s3://{{ bucket_name }}/{{ s3_pcplus_prefix }}/{{ oldest_quarter }}/ --recursive --profile {{ aws_profile_shared }}
      register: del
      failed_when: del.rc != 0

    - name: Upload new quarterly data
      command: >
        aws s3 cp --recursive {{ extract_dir }}/pcplus/data/ s3://{{ bucket_name }}/{{ s3_pcplus_prefix }}/{{ current_quarter }}/ --profile {{ aws_profile_shared }}
      register: upload_data
      failed_when: upload_data.rc != 0

    - name: Copy licence from previous quarter
      command: >
        aws s3 cp s3://{{ bucket_name }}/{{ s3_pcplus_prefix }}/{{ previous_quarter }}/pcplus.lic s3://{{ bucket_name }}/{{ s3_pcplus_prefix }}/{{ current_quarter }}/pcplus.lic --profile {{ aws_profile_shared }}
      register: lic_copy
      failed_when: lic_copy.rc != 0

  rescue:
    - debug:
        msg: " Failed to update S3 quarterly folders"
    - meta: end_play
