[staging]
#chips-oltp-db-01.staging.heritage.aws.internal
chips-oltp-db-02.staging.heritage.aws.internal
#chips-dba-dev-01.staging.heritage.aws.internal

[live]
#chips-oltp-db-01.live.heritage.aws.internal
#chips-oltp-db-02.live.heritage.aws.internal
#chips-reginit-01.live.heritage.aws.internal

#ansible -i inventories/heritage.ini staging -m ping
#ansible-playbook -i inventories/heritage.ini playbook.yml -l staging

