cloudwatch_agent_ctl: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl"
cloudwatch_config_path: "/opt/aws/amazon-cloudwatch-agent/etc/"
cloudwatch_config_file: "amazon-cloudwatch-agent.json"

working_dir: "/tmp/"
