---
- name: Download COMPA14 ZIP
  ansible.builtin.get_url:
    url: "{{ pcplus_download_url }}"
    dest: "{{ pcplus_local_zip_path }}"
    mode: "0644"
  notify: Unzip_compa14

- name: Verify pcplus/data exists locally
  ansible.builtin.stat:
    path: "{{ pcplus_extract_path }}/data"
  register: pcplus_data_stat

- name: Delete a file
  ansible.builtin.file:
    path: "{{ pcplus_local_zip_path }}/COMPA14.zip"
    state: absent

