---
- name: Ensure new quarter folder exists
  ansible.builtin.command:
    cmd: >
      aws s3api put-object --bucket "{{ pcplus_s3_bucket }}" --key "{{ pcplus_s3_prefix }}/{{ pcplus_new_folder }}/"
  changed_when: false

- name: Delete oldest quarter folder
  ansible.builtin.command:
    cmd: >
      aws s3 rm "s3://{{ pcplus_s3_bucket }}/{{ pcplus_s3_prefix }}/{{ pcplus_old_folder }}/" --recursive
  changed_when: false
