- name: Copy pcplus.lic into data_new
  ansible.builtin.command: >
    aws s3 cp
    s3://{{ pcplus_run_server_update_pcplus_bucket }}/pcplus/pcplus.lic
    {{ pcplus_run_server_update_pcplus_dir }}/{{ pcplus_run_server_update_pcplus_new_dir }}/pcplus.lic
    --region {{ pcplus_run_server_update_aws_region }}
  register: pcplus_copy_lic
  retries: 3
  delay: 5
  until: pcplus_copy_lic.rc == 0
  changed_when: "'download:' in pcplus_copy_lic.stdout"
  failed_when: pcplus_copy_lic.rc != 0
  become: true


