
afd_zip_url: "https://download.afd.co.uk/Support/COMPA14.zip"
download_dir: "/root/AFD"
extract_dir: "{{ download_dir }}"
bucket_name: "shared-services.eu-west-2.resources.ch.gov.uk"
s3_pcplus_prefix: "pcplus"
aws_profile_shared: "shared-services-eu-west-2"
aws_profile_heritage: "heritage-staging-eu-west-2"
pcplus_dir: "/opt/pcplus"
current_quarter: "{{ '%Y_Q%q' | strftime }}"
