---
pcplus_server_stage_aws_region: "eu-west-2"
pcplus_server_stage_s3_bucket: "shared-services.eu-west-2.resources.ch.gov.uk"
pcplus_server_stage_s3_prefix: "pcplus"

pcplus_server_stage__year: "{{ ansible_date_time.year | int }}"
pcplus_server_stage__month: "{{ ansible_date_time.month | int }}"
pcplus_server_stage__q: "{{ (((pcplus_server_stage__month | int) - 1) // 3) + 1 }}"

pcplus_server_stage_current_quarter: "{{ (pcplus_server_stage__year | int) }}_Q{{ pcplus_server_stage__q }}"

pcplus_server_stage_pcplus_dir: "/opt/pcplus"
pcplus_server_stage_target_dir: "{{ pcplus_server_stage_pcplus_dir }}/data_{{ pcplus_server_stage_current_quarter }}"
