---
# NetApp
storage_fsx_configure_netapp_hostname: null
storage_fsx_configure_netapp_username: null
storage_fsx_configure_netapp_password: null

# SVM and CIFS
storage_fsx_configure_vserver: null
storage_fsx_configure_cifs_server_name: null
storage_fsx_configure_cifs_domain: null
storage_fsx_configure_dns_servers: [] # e.g. ["1.2.3.4", "5.6.7.8"]

# AD
storage_fsx_configure_dc_admin_user_name: null
storage_fsx_configure_dc_admin_password: null
storage_fsx_configure_dc_ou: null

# FSx Users
storage_fsx_configure_fsx_domain_admins: [] # e.g. ["samjones", "alexwilliams"]
