---
- name: Download amazon-cloudwatch-agent public key
  ansible.builtin.get_url:
    url: "https://amazoncloudwatch-agent.s3.amazonaws.com/assets/amazon-cloudwatch-agent.gpg"
    dest: "{{ working_dir }}/amazon-cloudwatch-agent.gpg"

- name: Download amazon-cloudwatch-agent.rpm.sig file
  ansible.builtin.get_url:
    url: "https://amazoncloudwatch-agent.s3.amazonaws.com/redhat/{{ arch_name }}/latest/{{ cloudwatch_pkg }}.rpm.sig"
    dest: "{{ working_dir }}/amazon-cloudwatch-agent.rpm.sig"

- name: Get fingerprint from amazon-cloudwatch-agent public key
  ansible.builtin.shell: sq packet dump amazon-cloudwatch-agent.gpg | grep Fingerprint | awk '{print $NF}'
  register: gpg_fingerprint
  args:
    chdir: "{{ working_dir }}"

- name: Debug gpg_fingerprint
  ansible.builtin.debug:
    var: gpg_fingerprint.stdout

- name: Get fingerprint from AWS documentation
  ansible.builtin.shell: lynx -dump -nolist https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/verify-CloudWatch-Agent-Package-Signature.html | grep -m 1 -A 1 "The fingerprint string should" | tail -n 1 | tr -d " "
  register: doc_fingerprint
  args:
    chdir: "{{ working_dir }}"

- name: Debug gpg_fingerprint
  ansible.builtin.debug:
    var: doc_fingerprint.stdout

- name: Download amazon-cloudwatch-agent.rpm file if fingeprint matches
  ansible.builtin.get_url:
    url: "https://amazoncloudwatch-agent.s3.amazonaws.com/redhat/{{ arch_name }}/latest/{{ cloudwatch_pkg }}.rpm"
    dest: "{{ working_dir }}/{{ cloudwatch_pkg }}.rpm"
  when: gpg_fingerprint.stdout == doc_fingerprint.stdout

- name: Install {{ cloudwatch_package }}.rpm on {{ ansible_distribution }} 10
  ansible.builtin.dnf:
    name: "{{ working_dir }}/{{ cloudwatch_pkg }}.rpm"
    disable_gpg_check: true
    state: present
  when: >
    ansible_os_family == 'RedHat' and (
      ansible_distribution == 'RedHat' or
      ansible_distribution == 'Rocky'
    ) and (
      ansible_distribution_major_version == '10' 
    )
  ignore_errors: "{{ ansible_check_mode }}"
